package com.myspace.argoz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("MessageResponseDTO")
public class MessageResponseDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String message;
	@org.kie.api.definition.type.Label("codigo respuesta")
	private java.lang.String statusCode;

	public MessageResponseDTO() {
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(java.lang.String statusCode) {
		this.statusCode = statusCode;
	}

	public MessageResponseDTO(java.lang.String message,
			java.lang.String statusCode) {
		this.message = message;
		this.statusCode = statusCode;
	}

}